#!/usr/bin/env sh
set -eu

ACTION=install
NO_BUILD=0
OPEN_DASHBOARD=0
TIMEOUT_SECONDS=300

while [ "$#" -gt 0 ]; do
  case "$1" in
    install|start|restart|stop|status|logs) ACTION="$1" ;;
    --no-build) NO_BUILD=1 ;;
    --open) OPEN_DASHBOARD=1 ;;
    --timeout)
      shift
      [ "$#" -gt 0 ] || { echo 'Missing value for --timeout.' >&2; exit 2; }
      TIMEOUT_SECONDS="$1"
      ;;
    -h|--help)
      cat <<'EOF'
OpenMycelium product launcher

Usage:
  ./install.sh [install|start|restart|stop|status|logs] [options]

Options:
  --no-build       Start existing images without rebuilding
  --open           Open the dashboard after readiness checks pass
  --timeout SEC    Readiness timeout (default: 300)
EOF
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

PROJECT_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
STATE_DIRECTORY="$PROJECT_ROOT/.openmycelium"
LOG_FILE="$STATE_DIRECTORY/installer.log"
ERROR_LOG="$STATE_DIRECTORY/installer-error.log"
ENV_FILE="$PROJECT_ROOT/.env"
DASHBOARD_URL=http://127.0.0.1:8081
PROMETHEUS_URL=http://127.0.0.1:9090
GRAFANA_URL=http://127.0.0.1:3000
GENERATED_ADMIN_PASSWORD=
ADMIN_EMAIL=
SITE_ID=

mkdir -p "$STATE_DIRECTORY"
cd "$PROJECT_ROOT"

if [ -t 1 ]; then
  C_WHITE='\033[97m'; C_GRAY='\033[90m'; C_GREEN='\033[32m'; C_CYAN='\033[36m'; C_YELLOW='\033[33m'; C_RED='\033[31m'; C_RESET='\033[0m'
else
  C_WHITE=; C_GRAY=; C_GREEN=; C_CYAN=; C_YELLOW=; C_RED=; C_RESET=
fi

write_brand() {
  printf '\n'
  printf "${C_WHITE}  OM  OPENMYCELIUM${C_RESET}\n"
  printf "${C_GRAY}      HETEROGENEOUS AI CONTROL PLANE${C_RESET}\n"
  printf "${C_GRAY}  ------------------------------------------------------------${C_RESET}\n"
  printf '  Vendor-neutral infrastructure for models, agents, and compute\n\n'
}

make_bar() {
  bar_percent=$1
  bar_filled=$((bar_percent / 5))
  bar_index=0
  bar_value=
  while [ "$bar_index" -lt 20 ]; do
    if [ "$bar_index" -lt "$bar_filled" ]; then bar_value="${bar_value}#"; else bar_value="${bar_value}-"; fi
    bar_index=$((bar_index + 1))
  done
  printf '%s' "$bar_value"
}

write_stage() {
  stage_percent=$1; stage_label=$2; stage_state=${3:-OK}
  stage_color=$C_GREEN
  case "$stage_state" in RUN) stage_color=$C_CYAN ;; WARN) stage_color=$C_YELLOW ;; FAIL) stage_color=$C_RED ;; esac
  printf "${stage_color}  [%s] %3s%%  %-34s %s${C_RESET}\n" "$(make_bar "$stage_percent")" "$stage_percent" "$stage_label" "$stage_state"
}

random_hex() {
  random_bytes=${1:-24}
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$random_bytes"
  else
    od -An -N "$random_bytes" -tx1 /dev/urandom | tr -d ' \n'
  fi
}

get_env_value() {
  env_name=$1
  [ -f "$ENV_FILE" ] || return 0
  sed -n "s/^${env_name}=//p" "$ENV_FILE" | tail -n 1 | tr -d '\r'
}

ensure_configuration() {
  if [ ! -f "$ENV_FILE" ]; then
    SITE_ID="OM-$(random_hex 5 | tr '[:lower:]' '[:upper:]')"
    ADMIN_EMAIL=admin@openmycelium.local
    GENERATED_ADMIN_PASSWORD="OM-$(random_hex 14)"
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by the OpenMycelium installer. Do not commit this file.
OPENMYCELIUM_SITE_ID=$SITE_ID
BOOTSTRAP_ADMIN_EMAIL=$ADMIN_EMAIL
BOOTSTRAP_ADMIN_PASSWORD=$GENERATED_ADMIN_PASSWORD
CLUSTER_CREDENTIAL_KEY=$(random_hex 32)
AUTH_MODE=local
COOKIE_SECURE=false
METRICS_TOKEN=$(random_hex 32)
PROMETHEUS_PUBLIC_URL=http://127.0.0.1:9090
GRAFANA_PUBLIC_URL=http://127.0.0.1:3000
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=OM-$(random_hex 14)
AGENT_TOKEN=$(random_hex 32)
EOF
    write_stage 18 'Secure first-run configuration' OK
    return
  fi

  SITE_ID=$(get_env_value OPENMYCELIUM_SITE_ID)
  if [ -z "$SITE_ID" ]; then
    SITE_ID="OM-$(random_hex 5 | tr '[:lower:]' '[:upper:]')"
    printf '\nOPENMYCELIUM_SITE_ID=%s\n' "$SITE_ID" >> "$ENV_FILE"
  fi
  ADMIN_EMAIL=$(get_env_value BOOTSTRAP_ADMIN_EMAIL)
  write_stage 18 'Existing secure configuration' OK
}

assert_docker_runtime() {
  command -v docker >/dev/null 2>&1 || {
    printf '%s\n' 'Docker Desktop or Docker Engine with Compose v2 is required.' >&2
    exit 1
  }
  server_version=$(docker version --format '{{.Server.Version}}' 2>/dev/null || true)
  [ -n "$server_version" ] || {
    printf '%s\n' 'Docker is installed, but its engine is not running.' >&2
    exit 1
  }
  compose_version=$(docker compose version --short 2>/dev/null || true)
  [ -n "$compose_version" ] || { printf '%s\n' 'Docker Compose v2 is required.' >&2; exit 1; }
  write_stage 8 "Docker $server_version / Compose $compose_version" OK
}

run_compose_stage() {
  compose_label=$1; compose_start=$2; compose_end=$3
  shift 3
  : > "$LOG_FILE"
  : > "$ERROR_LOG"
  docker compose "$@" >"$LOG_FILE" 2>"$ERROR_LOG" &
  compose_pid=$!
  compose_started=$(date +%s)
  compose_frame=0
  while kill -0 "$compose_pid" 2>/dev/null; do
    compose_elapsed=$(( $(date +%s) - compose_started ))
    compose_range=$((compose_end - compose_start))
    compose_percent=$((compose_start + (compose_elapsed * compose_range / TIMEOUT_SECONDS)))
    [ "$compose_percent" -lt "$compose_end" ] || compose_percent=$((compose_end - 1))
    case $((compose_frame % 4)) in 0) spinner='|' ;; 1) spinner='/' ;; 2) spinner='-' ;; *) spinner='\' ;; esac
    printf "${C_CYAN}\r  [%s] %3s%%  %-34s %s${C_RESET}" "$(make_bar "$compose_percent")" "$compose_percent" "$compose_label" "$spinner"
    sleep 1
    compose_frame=$((compose_frame + 1))
  done
  if wait "$compose_pid"; then compose_code=0; else compose_code=$?; fi
  printf '\r%88s\r' ' '
  if [ "$compose_code" -ne 0 ]; then
    write_stage "$compose_start" "$compose_label" FAIL
    printf "${C_RED}\n  Docker output:${C_RESET}\n"
    tail -n 20 "$ERROR_LOG" 2>/dev/null || true
    printf "\n  Full log: %s\n" "$LOG_FILE"
    exit "$compose_code"
  fi
  write_stage "$compose_end" "$compose_label" OK
}

test_endpoint() {
  curl --fail --silent --show-error --max-time 3 "$1" >/dev/null 2>&1
}

wait_for_endpoint() {
  wait_url=$1; wait_label=$2; wait_start=$3; wait_end=$4; wait_timeout=$5; wait_optional=${6:-0}
  wait_started=$(date +%s)
  while :; do
    if test_endpoint "$wait_url"; then
      printf '\r%88s\r' ' '
      write_stage "$wait_end" "$wait_label" OK
      return 0
    fi
    wait_elapsed=$(( $(date +%s) - wait_started ))
    if [ "$wait_elapsed" -ge "$wait_timeout" ]; then break; fi
    wait_percent=$((wait_start + (wait_elapsed * (wait_end - wait_start) / wait_timeout)))
    [ "$wait_percent" -lt "$wait_end" ] || wait_percent=$((wait_end - 1))
    printf "${C_CYAN}\r  [%s] %3s%%  %-34s WAIT${C_RESET}" "$(make_bar "$wait_percent")" "$wait_percent" "$wait_label"
    sleep 1
  done
  printf '\r%88s\r' ' '
  if [ "$wait_optional" -eq 1 ]; then write_stage "$wait_end" "$wait_label" WARN; return 0; fi
  write_stage "$wait_start" "$wait_label" FAIL
  printf '  %s did not become ready. Run ./install.sh logs for details.\n' "$wait_label" >&2
  exit 1
}

show_ready_summary() {
  printf '\n'
  printf "${C_GREEN}  +----------------------------------------------------------+${C_RESET}\n"
  printf "${C_GREEN}  |  OPENMYCELIUM IS READY                                   |${C_RESET}\n"
  printf "${C_GREEN}  +----------------------------------------------------------+${C_RESET}\n"
  printf '  |  Site ID       %-41s|\n' "$SITE_ID"
  printf '  |  Control plane %-41s|\n' "$DASHBOARD_URL"
  printf '  |  Prometheus    %-41s|\n' "$PROMETHEUS_URL"
  printf '  |  Grafana       %-41s|\n' "$GRAFANA_URL"
  printf "${C_GREEN}  +----------------------------------------------------------+${C_RESET}\n"
  if [ -n "$GENERATED_ADMIN_PASSWORD" ]; then
    printf "\n${C_YELLOW}  First-run administrator credentials - save these now:${C_RESET}\n"
    printf '  Email:    %s\n' "$ADMIN_EMAIL"
    printf '  Password: %s\n' "$GENERATED_ADMIN_PASSWORD"
  fi
  printf '\n  Lifecycle commands:\n'
  printf '    ./install.sh status\n    ./install.sh restart\n    ./install.sh logs\n    ./install.sh stop\n\n'
}

open_dashboard() {
  [ "$OPEN_DASHBOARD" -eq 1 ] || {
    printf "${C_CYAN}  Launch dashboard: %s${C_RESET}\n" "$DASHBOARD_URL"
    return
  }
  if command -v open >/dev/null 2>&1; then open "$DASHBOARD_URL"
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$DASHBOARD_URL" >/dev/null 2>&1 &
  else printf '  Open %s in your browser.\n' "$DASHBOARD_URL"; fi
}

start_openmycelium() {
  ensure_configuration
  if [ "$1" -eq 1 ]; then
    run_compose_stage 'Assembling product images' 24 72 up -d --remove-orphans --build
  else
    run_compose_stage 'Starting product services' 24 72 up -d --remove-orphans
  fi
  wait_for_endpoint "$DASHBOARD_URL/api/v1/ready" 'Control plane and data services' 72 90 "$TIMEOUT_SECONDS" 0
  wait_for_endpoint "$PROMETHEUS_URL/-/ready" 'Prometheus telemetry' 90 95 60 1
  wait_for_endpoint "$GRAFANA_URL/api/health" 'Grafana operations console' 95 99 60 1
  write_stage 100 'OpenMycelium product fabric' OK
  show_ready_summary
  open_dashboard
}

write_brand
assert_docker_runtime

case "$ACTION" in
  install) if [ "$NO_BUILD" -eq 1 ]; then start_openmycelium 0; else start_openmycelium 1; fi ;;
  start) start_openmycelium 0 ;;
  restart)
    ensure_configuration
    run_compose_stage 'Restarting product services' 24 72 restart
    wait_for_endpoint "$DASHBOARD_URL/api/v1/ready" 'Control plane and data services' 72 99 "$TIMEOUT_SECONDS" 0
    write_stage 100 'OpenMycelium product fabric' OK
    show_ready_summary
    open_dashboard
    ;;
  stop)
    ensure_configuration
    run_compose_stage 'Stopping product services' 20 100 down --remove-orphans
    printf "\n${C_GREEN}  OpenMycelium stopped. Persistent volumes were preserved.${C_RESET}\n\n"
    ;;
  status)
    ensure_configuration
    write_stage 30 'Reading product service state' RUN
    docker compose ps
    if test_endpoint "$DASHBOARD_URL/api/v1/ready"; then write_stage 100 'Control plane readiness' OK; else write_stage 100 'Control plane readiness' WARN; fi
    printf '\n  Site ID: %s\n  Dashboard: %s\n\n' "$SITE_ID" "$DASHBOARD_URL"
    ;;
  logs)
    ensure_configuration
    printf "${C_CYAN}  Streaming OpenMycelium logs. Press Ctrl+C to stop.${C_RESET}\n"
    docker compose logs --tail 200 -f openmycelium postgres nats prometheus grafana
    ;;
esac
