[CmdletBinding()]
param(
    [ValidateSet('Install', 'Start', 'Restart', 'Stop', 'Status', 'Logs')]
    [string]$Action = 'Install',
    [switch]$NoBuild,
    [switch]$Open,
    [ValidateRange(30, 900)]
    [int]$TimeoutSeconds = 300
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$StateDirectory = Join-Path $ProjectRoot '.openmycelium'
$LogFile = Join-Path $StateDirectory 'installer.log'
$ErrorLog = Join-Path $StateDirectory 'installer-error.log'
$EnvFile = Join-Path $ProjectRoot '.env'
$DashboardUrl = 'http://127.0.0.1:8081'
$PrometheusUrl = 'http://127.0.0.1:9090'
$GrafanaUrl = 'http://127.0.0.1:3000'
$script:GeneratedAdminPassword = ''
$script:AdminEmail = ''
$script:SiteId = ''

Set-Location $ProjectRoot
New-Item -ItemType Directory -Path $StateDirectory -Force | Out-Null

function Write-Brand {
    Clear-Host
    Write-Host ''
    Write-Host '  OM  OPENMYCELIUM' -ForegroundColor White
    Write-Host '      HETEROGENEOUS AI CONTROL PLANE' -ForegroundColor DarkGray
    Write-Host '  ------------------------------------------------------------' -ForegroundColor DarkGray
    Write-Host '  Vendor-neutral infrastructure for models, agents, and compute' -ForegroundColor Gray
    Write-Host ''
}

function Write-Stage {
    param(
        [int]$Percent,
        [string]$Label,
        [ValidateSet('RUN', 'OK', 'WARN', 'FAIL')]
        [string]$State = 'OK'
    )
    $filled = [Math]::Floor($Percent / 5)
    $bar = ('#' * $filled).PadRight(20, '-')
    $color = switch ($State) {
        'RUN' { 'Cyan' }
        'OK' { 'Green' }
        'WARN' { 'Yellow' }
        'FAIL' { 'Red' }
    }
    Write-Host ('  [{0}] {1,3}%  {2,-34} {3}' -f $bar, $Percent, $Label, $State) -ForegroundColor $color
}

function New-RandomHex {
    param([int]$Bytes = 24)
    $buffer = New-Object byte[] $Bytes
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $generator.GetBytes($buffer) } finally { $generator.Dispose() }
    return -join ($buffer | ForEach-Object { $_.ToString('x2') })
}

function Get-EnvValue {
    param([string]$Name)
    if (-not (Test-Path -LiteralPath $EnvFile)) { return '' }
    $line = Get-Content -LiteralPath $EnvFile | Where-Object { $_ -match ('^{0}=' -f [regex]::Escape($Name)) } | Select-Object -Last 1
    if (-not $line) { return '' }
    return ($line -split '=', 2)[1].Trim()
}

function Ensure-Configuration {
    if (-not (Test-Path -LiteralPath $EnvFile)) {
        $script:SiteId = 'OM-' + (New-RandomHex 5).ToUpperInvariant()
        $script:AdminEmail = 'admin@openmycelium.local'
        $script:GeneratedAdminPassword = 'OM-' + (New-RandomHex 14)
        $lines = @(
            '# Generated by the OpenMycelium installer. Do not commit this file.'
            "OPENMYCELIUM_SITE_ID=$script:SiteId"
            "BOOTSTRAP_ADMIN_EMAIL=$script:AdminEmail"
            "BOOTSTRAP_ADMIN_PASSWORD=$script:GeneratedAdminPassword"
            "CLUSTER_CREDENTIAL_KEY=$(New-RandomHex 32)"
            'AUTH_MODE=local'
            'COOKIE_SECURE=false'
            "METRICS_TOKEN=$(New-RandomHex 32)"
            'PROMETHEUS_PUBLIC_URL=http://127.0.0.1:9090'
            'GRAFANA_PUBLIC_URL=http://127.0.0.1:3000'
            'GRAFANA_ADMIN_USER=admin'
            "GRAFANA_ADMIN_PASSWORD=OM-$(New-RandomHex 14)"
            "AGENT_TOKEN=$(New-RandomHex 32)"
        )
        $encoding = New-Object System.Text.UTF8Encoding($false)
        [System.IO.File]::WriteAllText($EnvFile, (($lines -join [Environment]::NewLine) + [Environment]::NewLine), $encoding)
        Write-Stage 18 'Secure first-run configuration' 'OK'
        return
    }

    $script:SiteId = Get-EnvValue 'OPENMYCELIUM_SITE_ID'
    if (-not $script:SiteId) {
        $script:SiteId = 'OM-' + (New-RandomHex 5).ToUpperInvariant()
        [System.IO.File]::AppendAllText($EnvFile, ([Environment]::NewLine + "OPENMYCELIUM_SITE_ID=$script:SiteId" + [Environment]::NewLine))
    }
    $script:AdminEmail = Get-EnvValue 'BOOTSTRAP_ADMIN_EMAIL'
    Write-Stage 18 'Existing secure configuration' 'OK'
}

function Assert-DockerRuntime {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw 'Docker Desktop or Docker Engine with Compose v2 is required. Install Docker, start it, then run this command again.'
    }
    $serverVersion = & docker version --format '{{.Server.Version}}' 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $serverVersion) {
        throw 'Docker is installed, but its engine is not running. Start Docker Desktop or the Docker service, then try again.'
    }
    $composeVersion = & docker compose version --short 2>$null
    if ($LASTEXITCODE -ne 0) { throw 'Docker Compose v2 is required.' }
    Write-Stage 8 "Docker $serverVersion / Compose $composeVersion" 'OK'
}

function Invoke-ComposeStage {
    param(
        [string[]]$Arguments,
        [string]$Label,
        [int]$StartPercent,
        [int]$EndPercent
    )
    Remove-Item -LiteralPath $LogFile, $ErrorLog -Force -ErrorAction SilentlyContinue
    $commandArguments = @('compose') + $Arguments
    $dockerCommand = Get-Command docker -CommandType Application -ErrorAction Stop | Select-Object -First 1
    $startInfo = New-Object System.Diagnostics.ProcessStartInfo
    $startInfo.FileName = $dockerCommand.Source
    $startInfo.Arguments = $commandArguments -join ' '
    $startInfo.WorkingDirectory = $ProjectRoot
    $startInfo.UseShellExecute = $false
    $startInfo.CreateNoWindow = $true
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $startInfo
    if (-not $process.Start()) { throw 'Docker Compose could not be started.' }
    $outputTask = $process.StandardOutput.ReadToEndAsync()
    $errorTask = $process.StandardError.ReadToEndAsync()
    $started = Get-Date
    $spinner = @('|', '/', '-', '\')
    $frame = 0
    while (-not $process.HasExited) {
        $elapsed = ((Get-Date) - $started).TotalSeconds
        $range = [Math]::Max(1, $EndPercent - $StartPercent)
        $percent = [Math]::Min($EndPercent - 1, $StartPercent + [Math]::Floor(($elapsed / $TimeoutSeconds) * $range))
        $filled = [Math]::Floor($percent / 5)
        $bar = ('#' * $filled).PadRight(20, '-')
        Write-Host ("`r  [{0}] {1,3}%  {2,-34} {3}" -f $bar, $percent, $Label, $spinner[$frame % $spinner.Count]) -ForegroundColor Cyan -NoNewline
        Start-Sleep -Milliseconds 350
        $frame++
        $process.Refresh()
    }
    $process.WaitForExit()
    $exitCode = $process.ExitCode
    $standardOutput = $outputTask.GetAwaiter().GetResult()
    $errorOutput = $errorTask.GetAwaiter().GetResult()
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($ErrorLog, $errorOutput, $encoding)
    [System.IO.File]::WriteAllText($LogFile, ($standardOutput + [Environment]::NewLine + $errorOutput), $encoding)
    $process.Dispose()
    Write-Host "`r$(' ' * 88)`r" -NoNewline
    if ($exitCode -ne 0) {
        Write-Stage $StartPercent $Label 'FAIL'
        Write-Host "`n  Docker output:" -ForegroundColor Red
        if (Test-Path -LiteralPath $ErrorLog) { Get-Content -LiteralPath $ErrorLog -Tail 20 | ForEach-Object { Write-Host "  $_" -ForegroundColor DarkRed } }
        Write-Host "`n  Full log: $LogFile" -ForegroundColor DarkGray
        throw "Docker Compose exited with code $exitCode."
    }
    Write-Stage $EndPercent $Label 'OK'
}

function Test-HttpEndpoint {
    param([string]$Url)
    try {
        $response = Invoke-WebRequest -UseBasicParsing -Uri $Url -TimeoutSec 3
        return $response.StatusCode -ge 200 -and $response.StatusCode -lt 300
    } catch { return $false }
}

function Wait-ForEndpoint {
    param(
        [string]$Url,
        [string]$Label,
        [int]$StartPercent,
        [int]$EndPercent,
        [int]$Timeout = 120,
        [switch]$Optional
    )
    $started = Get-Date
    do {
        if (Test-HttpEndpoint $Url) {
            Write-Host "`r$(' ' * 88)`r" -NoNewline
            Write-Stage $EndPercent $Label 'OK'
            return $true
        }
        $elapsed = ((Get-Date) - $started).TotalSeconds
        $percent = [Math]::Min($EndPercent - 1, $StartPercent + [Math]::Floor(($elapsed / $Timeout) * ($EndPercent - $StartPercent)))
        $filled = [Math]::Floor($percent / 5)
        $bar = ('#' * $filled).PadRight(20, '-')
        Write-Host ("`r  [{0}] {1,3}%  {2,-34} WAIT" -f $bar, $percent, $Label) -ForegroundColor Cyan -NoNewline
        Start-Sleep -Seconds 1
    } while (((Get-Date) - $started).TotalSeconds -lt $Timeout)
    Write-Host "`r$(' ' * 88)`r" -NoNewline
    if ($Optional) { Write-Stage $EndPercent $Label 'WARN'; return $false }
    Write-Stage $StartPercent $Label 'FAIL'
    throw "$Label did not become ready within $Timeout seconds. Run '.\install.ps1 -Action Logs' for details."
}

function Show-ReadySummary {
    Write-Host ''
    Write-Host '  +----------------------------------------------------------+' -ForegroundColor Green
    Write-Host '  |  OPENMYCELIUM IS READY                                   |' -ForegroundColor Green
    Write-Host '  +----------------------------------------------------------+' -ForegroundColor Green
    Write-Host ('  |  Site ID       {0,-41}|' -f $script:SiteId) -ForegroundColor White
    Write-Host ('  |  Control plane {0,-41}|' -f $DashboardUrl) -ForegroundColor White
    Write-Host ('  |  Prometheus    {0,-41}|' -f $PrometheusUrl) -ForegroundColor Gray
    Write-Host ('  |  Grafana       {0,-41}|' -f $GrafanaUrl) -ForegroundColor Gray
    Write-Host '  +----------------------------------------------------------+' -ForegroundColor Green
    if ($script:GeneratedAdminPassword) {
        Write-Host ''
        Write-Host '  First-run administrator credentials - save these now:' -ForegroundColor Yellow
        Write-Host "  Email:    $script:AdminEmail" -ForegroundColor White
        Write-Host "  Password: $script:GeneratedAdminPassword" -ForegroundColor White
    }
    Write-Host ''
    Write-Host '  Lifecycle commands:' -ForegroundColor DarkGray
    Write-Host '    .\install.ps1 -Action Status' -ForegroundColor Gray
    Write-Host '    .\install.ps1 -Action Restart' -ForegroundColor Gray
    Write-Host '    .\install.ps1 -Action Logs' -ForegroundColor Gray
    Write-Host '    .\install.ps1 -Action Stop' -ForegroundColor Gray
    Write-Host ''
}

function Start-OpenMycelium {
    param([switch]$Build)
    Ensure-Configuration
    $arguments = @('up', '-d', '--remove-orphans')
    if ($Build) { $arguments += '--build' }
    Invoke-ComposeStage -Arguments $arguments -Label ($(if ($Build) { 'Assembling product images' } else { 'Starting product services' })) -StartPercent 24 -EndPercent 72
    Wait-ForEndpoint -Url "$DashboardUrl/api/v1/ready" -Label 'Control plane and data services' -StartPercent 72 -EndPercent 90 -Timeout $TimeoutSeconds | Out-Null
    Wait-ForEndpoint -Url "$PrometheusUrl/-/ready" -Label 'Prometheus telemetry' -StartPercent 90 -EndPercent 95 -Timeout 60 -Optional | Out-Null
    Wait-ForEndpoint -Url "$GrafanaUrl/api/health" -Label 'Grafana operations console' -StartPercent 95 -EndPercent 99 -Timeout 60 -Optional | Out-Null
    Write-Stage 100 'OpenMycelium product fabric' 'OK'
    Show-ReadySummary
    if ($Open) {
        Write-Host "  Opening $DashboardUrl" -ForegroundColor Cyan
        Start-Process $DashboardUrl
    } else {
        Write-Host "  Launch dashboard: Start-Process '$DashboardUrl'" -ForegroundColor Cyan
    }
}

try {
    Write-Brand
    Assert-DockerRuntime
    switch ($Action.ToLowerInvariant()) {
        'install' { Start-OpenMycelium -Build:(-not $NoBuild) }
        'start' { Start-OpenMycelium }
        'restart' {
            Ensure-Configuration
            Invoke-ComposeStage -Arguments @('restart') -Label 'Restarting product services' -StartPercent 24 -EndPercent 72
            Wait-ForEndpoint -Url "$DashboardUrl/api/v1/ready" -Label 'Control plane and data services' -StartPercent 72 -EndPercent 99 -Timeout $TimeoutSeconds | Out-Null
            Write-Stage 100 'OpenMycelium product fabric' 'OK'
            Show-ReadySummary
            if ($Open) { Start-Process $DashboardUrl }
        }
        'stop' {
            Ensure-Configuration
            Invoke-ComposeStage -Arguments @('down', '--remove-orphans') -Label 'Stopping product services' -StartPercent 20 -EndPercent 100
            Write-Host "`n  OpenMycelium stopped. Persistent volumes were preserved.`n" -ForegroundColor Green
        }
        'status' {
            Ensure-Configuration
            Write-Stage 30 'Reading product service state' 'RUN'
            & docker compose ps
            $ready = Test-HttpEndpoint "$DashboardUrl/api/v1/ready"
            Write-Stage 100 'Control plane readiness' $(if ($ready) { 'OK' } else { 'WARN' })
            Write-Host "`n  Site ID: $script:SiteId`n  Dashboard: $DashboardUrl`n"
        }
        'logs' {
            Ensure-Configuration
            Write-Host '  Streaming OpenMycelium logs. Press Ctrl+C to stop.' -ForegroundColor Cyan
            & docker compose logs --tail 200 -f openmycelium postgres nats prometheus grafana
        }
    }
} catch {
    Write-Host "`n  INSTALLATION STOPPED" -ForegroundColor Red
    Write-Host "  $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "  Diagnostic log: $LogFile`n" -ForegroundColor DarkGray
    exit 1
}
